import { StyleSheet, Dimensions } from 'react-native';
import theme from '../../theme/theme';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0D18',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  supportHeader: {
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.xl,
    paddingBottom: theme.spacing.sm,
  },
  headerActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  headerProfileAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 12,
  },
  headerTitleText: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.colors.textPrimary,
  },
  bellBtn: {
    position: 'relative',
    padding: 4,
  },
  bellBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: '#FF4081',
    borderRadius: 5,
    width: 10,
    height: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: {
    color: 'white',
    fontSize: 6,
    fontWeight: 'bold',
  },
  headerSubtitleText: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    fontWeight: '500',
  },
  mainSupportLinks: {
    paddingHorizontal: theme.spacing.lg,
    marginTop: 10,
  },
  supportLinkCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.colors.bgCard,
    borderWidth: 1,
    borderColor: theme.colors.borderColor,
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
  },
  cardLeftInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  supportIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: 'rgba(123, 31, 162, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  supportTextDetails: {
    flex: 1,
  },
  supportCardTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.colors.textPrimary,
  },
  supportCardDesc: {
    fontSize: 10,
    color: theme.colors.textSecondary,
    marginTop: 2,
  },
  cardChevron: {
    color: theme.colors.textSecondary,
  },
  supportHoursCard: {
    backgroundColor: theme.colors.bgCard,
    borderWidth: 1,
    borderColor: theme.colors.borderColor,
    borderRadius: 24,
    marginHorizontal: theme.spacing.lg,
    marginVertical: theme.spacing.sm,
    padding: theme.spacing.md,
    position: 'relative',
    overflow: 'hidden',
  },
  hoursCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  hoursIcon: {
    marginRight: 10,
  },
  hoursTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.textPrimary,
  },
  hoursTable: {
    width: '100%',
    marginBottom: 16,
  },
  hoursRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.04)',
  },
  hoursDay: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.textSecondary,
  },
  hoursTime: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.textPrimary,
  },
  statusClosed: {
    color: '#FF5252',
  },
  hoursDisclaimer: {
    fontSize: 10,
    color: theme.colors.textMuted,
    lineHeight: 14,
  },
  reachUsSection: {
    marginHorizontal: theme.spacing.lg,
    marginVertical: theme.spacing.sm,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    marginBottom: 12,
  },
  reachUsGrid: {
    width: '100%',
  },
  reachCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.colors.bgCard,
    borderWidth: 1,
    borderColor: theme.colors.borderColor,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
  },
  reachIconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  emailBg: {
    backgroundColor: 'rgba(123, 31, 162, 0.15)',
  },
  callBg: {
    backgroundColor: 'rgba(41, 182, 246, 0.15)',
  },
  reachDetails: {
    flex: 1,
  },
  reachHeading: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.textPrimary,
  },
  reachSubtext: {
    fontSize: 10,
    color: theme.colors.textSecondary,
    marginTop: 2,
  },
  reachArrow: {
    color: theme.colors.textSecondary,
  },
  weCareCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(123, 31, 162, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(123, 31, 162, 0.2)',
    borderRadius: 20,
    marginHorizontal: theme.spacing.lg,
    marginVertical: theme.spacing.sm,
    padding: 16,
  },
  careLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  careIconBox: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(123, 31, 162, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  careText: {
    flex: 1,
  },
  careTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#B085F5',
  },
  careDesc: {
    fontSize: 10,
    color: theme.colors.textSecondary,
    lineHeight: 14,
    marginTop: 2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
  },
  chatModalContent: {
    backgroundColor: '#0F121E',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    height: '80%',
    paddingBottom: 20,
  },
  chatModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  chatHeaderProfile: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  botAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#7B1FA2',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  chatBotName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  botStatusIndicator: {
    fontSize: 9,
    color: '#4CAF50',
    fontWeight: '600',
    marginTop: 1,
  },
  chatCloseBtn: {
    padding: 4,
  },
  chatMessagesLog: {
    flex: 1,
    padding: 16,
  },
  chatBubbleRow: {
    flexDirection: 'row',
    marginBottom: 12,
    width: '100%',
  },
  botRow: {
    justifyContent: 'flex-start',
  },
  userRow: {
    justifyContent: 'flex-end',
  },
  chatBubble: {
    maxWidth: '75%',
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  botBubble: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  userBubble: {
    backgroundColor: '#7B1FA2',
    borderBottomRightRadius: 4,
  },
  chatBubbleText: {
    fontSize: 12,
    color: '#FFFFFF',
    lineHeight: 16,
  },
  typingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  dot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#90A4AE',
    marginHorizontal: 2,
  },
  chatInputForm: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
  },
  chatInputField: {
    flex: 1,
    backgroundColor: '#0A0D18',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: 12,
    height: 40,
    paddingHorizontal: 12,
    color: '#FFFFFF',
    fontSize: 12,
    marginRight: 10,
  },
  chatSendBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#7B1FA2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  faqModalContent: {
    backgroundColor: '#0F121E',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    height: '75%',
    paddingBottom: 20,
  },
  faqModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  faqModalTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  faqCloseBtn: {
    padding: 4,
  },
  faqAccordionList: {
    flex: 1,
    padding: 16,
  },
  faqAccordionItem: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.04)',
    marginBottom: 8,
  },
  faqQuestionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
  },
  faqQuestionText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
    flex: 1,
    marginRight: 10,
  },
  faqArrowIcon: {
    color: theme.colors.textSecondary,
  },
  faqAnswerRow: {
    paddingBottom: 14,
    paddingHorizontal: 2,
  },
  faqAnswerText: {
    fontSize: 11,
    color: theme.colors.textSecondary,
    lineHeight: 16,
  },
});
