import { StyleSheet, Platform, StatusBar } from "react-native";

const statusBarHeight = Platform.OS === "android" ? StatusBar.currentHeight || 24 : 44;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#060813",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: statusBarHeight + 8,
    paddingBottom: 14,
    backgroundColor: "#090B13",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: 1.2,
  },
  tableCard: {
    margin: 16,
    backgroundColor: "#0F1221",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(176, 133, 245, 0.2)",
    overflow: "hidden",
  },
  tableHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#16192E",
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  tableHeaderCell: {
    fontSize: 10,
    fontWeight: "800",
    color: "#B085F5",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.04)",
    minHeight: 64,
  },
  tableRowEven: {
    backgroundColor: "rgba(255, 255, 255, 0.02)",
  },
  cellText: {
    fontSize: 12,
    color: "#FFFFFF",
    fontWeight: "500",
    lineHeight: 16,
  },
  colId: {
    flex: 1.0,
    paddingRight: 4,
  },
  colTitle: {
    flex: 3.2,
    paddingRight: 10,
  },
  colType: {
    flex: 1.6,
    paddingRight: 6,
  },
  colActions: {
    flex: 1.2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
  },
  actionEditBtn: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: "rgba(41, 182, 246, 0.15)",
  },
  actionDeleteBtn: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: "rgba(244, 67, 54, 0.15)",
  },
  // Detail View Styles
  detailCard: {
    margin: 16,
    backgroundColor: "#0F1221",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(176, 133, 245, 0.25)",
    padding: 20,
  },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  detailTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#FFFFFF",
    flex: 1,
    marginRight: 10,
  },
  detailActionRow: {
    flexDirection: "row",
    gap: 8,
  },
  detailEditBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#29B6F6",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  detailEditBtnText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 12,
  },
  detailDeleteBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#FF5252",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  detailDeleteBtnText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 12,
  },
  detailFieldGroup: {
    marginBottom: 16,
  },
  detailFieldLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#B085F5",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  detailFieldValue: {
    fontSize: 13,
    color: "#FFFFFF",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
});
