import { StyleSheet, Platform, StatusBar } from "react-native";

const statusBarHeight = Platform.OS === "android" ? StatusBar.currentHeight || 24 : 44;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#060813",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: statusBarHeight + 8,
    paddingBottom: 14,
    backgroundColor: "#090B13",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: 1.2,
  },
  tableCard: {
    margin: 16,
    backgroundColor: "#0F1221",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(176, 133, 245, 0.2)",
    overflow: "hidden",
  },
  tableHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#16192E",
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  tableHeaderCell: {
    fontSize: 10,
    fontWeight: "800",
    color: "#B085F5",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.04)",
  },
  tableRowEven: {
    backgroundColor: "rgba(255, 255, 255, 0.02)",
  },
  cellText: {
    fontSize: 12,
    color: "#FFFFFF",
    fontWeight: "500",
  },
  colId: {
    flex: 1.1,
  },
  colName: {
    flex: 2.4,
  },
  colWeeks: {
    flex: 1.2,
  },
  colActions: {
    flex: 1.1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  actionEditBtn: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: "rgba(41, 182, 246, 0.15)",
  },
  actionDeleteBtn: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: "rgba(244, 67, 54, 0.15)",
  },

  // Tree Hierarchy Styles
  treeCard: {
    margin: 16,
    backgroundColor: "#0F1221",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(176, 133, 245, 0.25)",
    padding: 16,
  },
  addPhaseBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(123, 31, 162, 0.25)",
    borderWidth: 1,
    borderColor: "rgba(176, 133, 245, 0.4)",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 16,
    gap: 8,
  },
  addPhaseBtnText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },
  phaseCard: {
    backgroundColor: "#16192E",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    marginBottom: 12,
    overflow: "hidden",
  },
  phaseHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 14,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
  },
  phaseHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  phaseTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: 0.5,
  },
  phaseBadge: {
    fontSize: 11,
    fontWeight: "600",
    color: "#B085F5",
    backgroundColor: "rgba(176, 133, 245, 0.15)",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    marginLeft: 6,
  },
  aspectContainer: {
    paddingLeft: 20,
    paddingRight: 12,
    paddingVertical: 8,
    borderLeftWidth: 2,
    borderLeftColor: "rgba(176, 133, 245, 0.3)",
    marginLeft: 16,
    marginBottom: 8,
  },
  aspectHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
    gap: 6,
  },
  aspectName: {
    fontSize: 12,
    fontWeight: "700",
    color: "#81D4FA",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  questionCard: {
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.04)",
  },
  questionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  questionText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#FFFFFF",
    flex: 1,
  },
  optionsList: {
    marginTop: 8,
    paddingLeft: 16,
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  optionText: {
    fontSize: 11,
    color: "rgba(255, 255, 255, 0.8)",
  },
  optionScore: {
    fontSize: 11,
    fontWeight: "700",
    color: "#00E676",
  },
  addSmallBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 6,
    paddingVertical: 4,
  },
  addSmallBtnText: {
    fontSize: 11,
    color: "#B085F5",
    fontWeight: "600",
  },
});
