import { StyleSheet, Platform, StatusBar } from "react-native";

const statusBarHeight = Platform.OS === "android" ? StatusBar.currentHeight || 24 : 44;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#060813",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: statusBarHeight + 8,
    paddingBottom: 14,
    backgroundColor: "#090B13",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: 1.2,
  },
  tableCard: {
    margin: 16,
    backgroundColor: "#0F1221",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(176, 133, 245, 0.2)",
    overflow: "hidden",
  },
  tableHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#16192E",
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  tableHeaderCell: {
    fontSize: 10,
    fontWeight: "800",
    color: "#B085F5",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.04)",
  },
  tableRowEven: {
    backgroundColor: "rgba(255, 255, 255, 0.02)",
  },
  cellText: {
    fontSize: 12,
    color: "#FFFFFF",
    fontWeight: "500",
  },
  colUserId: {
    flex: 2.2,
  },
  colLogDate: {
    flex: 2.2,
  },
  colActions: {
    flex: 1.1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  actionEditBtn: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: "rgba(41, 182, 246, 0.15)",
  },
  actionDeleteBtn: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: "rgba(244, 67, 54, 0.15)",
  },
  // Detail View Styles
  detailCard: {
    margin: 16,
    backgroundColor: "#0F1221",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(176, 133, 245, 0.25)",
    padding: 20,
  },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  detailTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#FFFFFF",
    flex: 1,
    marginRight: 8,
  },
  detailActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  detailEditBtn: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: "#29B6F6",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  detailEditBtnText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 11,
  },
  detailDeleteBtn: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: "#FF5252",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  detailDeleteBtnText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 11,
  },
  detailFieldGroup: {
    marginBottom: 16,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.04)",
  },
  detailFieldLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#B085F5",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 4,
  },
  detailFieldValue: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  // Read-only modal styles
  readOnlyNotice: {
    backgroundColor: "rgba(41, 182, 246, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(41, 182, 246, 0.3)",
    borderRadius: 10,
    padding: 12,
    marginBottom: 14,
  },
  readOnlyNoticeText: {
    fontSize: 11,
    color: "#81D4FA",
    lineHeight: 16,
    fontWeight: "600",
  },
});
