import { StyleSheet, Platform, StatusBar } from "react-native";

const statusBarHeight = Platform.OS === "android" ? StatusBar.currentHeight || 24 : 44;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#060813",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: statusBarHeight + 8,
    paddingBottom: 14,
    backgroundColor: "#090B13",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    alignItems: "center",
    justify.content: "center",
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: 1.2,
  },
  tableCard: {
    margin: 16,
    backgroundColor: "#0F1221",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(176, 133, 245, 0.2)",
    overflow: "hidden",
  },
  addBtnTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(123, 31, 162, 0.25)",
    borderWidth: 1,
    borderColor: "rgba(176, 133, 245, 0.4)",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 4,
    gap: 8,
  },
  addBtnTopText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },
  tableHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#16192E",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  tableHeaderCell: {
    fontSize: 10,
    fontWeight: "800",
    color: "#B085F5",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.04)",
  },
  tableRowEven: {
    backgroundColor: "rgba(255, 255, 255, 0.02)",
  },
  cellText: {
    fontSize: 12,
    color: "#FFFFFF",
    fontWeight: "500",
  },
  colId: {
    flex: 1.2,
  },
  colCategory: {
    flex: 2.2,
  },
  colActionsHeader: {
    flex: 1.2,
    textAlign: "right",
  },
  colActions: {
    flex: 1.2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  actionEditBtn: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: "rgba(41, 182, 246, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(41, 182, 246, 0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  actionDeleteBtn: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: "rgba(244, 67, 54, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(244, 67, 54, 0.3)",
    alignItems: "center",
    justifyContent: "center",
  },

  // Detail View Card
  detailCard: {
    margin: 16,
    backgroundColor: "#0F1221",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(176, 133, 245, 0.25)",
    padding: 16,
  },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  detailTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: 1,
    flex: 1,
    marginRight: 8,
  },
  fieldGroup: {
    marginBottom: 12,
  },
  fieldLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#B085F5",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  fieldValue: {
    fontSize: 13,
    color: "#FFFFFF",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderRadius: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  optionsSection: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
  },
  optionsSectionTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: "#81D4FA",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 10,
  },
  optionCardRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.04)",
  },
  optionTextLabel: {
    fontSize: 12,
    color: "#FFFFFF",
    fontWeight: "500",
    flex: 1,
    marginRight: 8,
  },
  optionScoreBadge: {
    fontSize: 11,
    fontWeight: "700",
    color: "#00E676",
    backgroundColor: "rgba(0, 230, 118, 0.15)",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  addOptionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
    paddingVertical: 6,
  },
  addOptionBtnText: {
    fontSize: 12,
    color: "#B085F5",
    fontWeight: "700",
  },
});
