import { StyleSheet, Dimensions, Platform, StatusBar } from "react-native";
import theme from "../../theme/theme";

const { width } = Dimensions.get("window");
const statusBarHeight = Platform.OS === "android" ? StatusBar.currentHeight || 24 : 44;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#060813",
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: statusBarHeight + 16,
    paddingBottom: 40,
  },
  glowPurple: {
    position: "absolute",
    top: -80,
    left: -80,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: "rgba(123, 31, 162, 0.25)",
    opacity: 0.8,
  },
  glowBlue: {
    position: "absolute",
    bottom: -80,
    right: -80,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: "rgba(41, 182, 246, 0.2)",
    opacity: 0.8,
  },
  authCard: {
    width: "100%",
    maxWidth: 440,
    backgroundColor: "#0F1221",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(176, 133, 245, 0.25)",
    padding: 20,
    marginVertical: 10,
    shadowColor: "#7B1FA2",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 24,
    elevation: 16,
  },
  brandHeader: {
    alignItems: "center",
    marginBottom: 16,
    marginTop: 4,
  },
  roleToggleWrapper: {
    flexDirection: "row",
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    borderRadius: 12,
    padding: 4,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  roleToggleBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 8,
  },
  roleToggleBtnActive: {
    backgroundColor: "#7B1FA2",
    shadowColor: "#7B1FA2",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
  },
  roleToggleText: {
    fontSize: 13,
    fontWeight: "600",
    color: "rgba(255, 255, 255, 0.6)",
  },
  roleToggleTextActive: {
    color: "#FFFFFF",
    fontWeight: "800",
  },
  brandLogoRing: {
    width: 64,
    height: 64,
    borderRadius: 32,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    borderWidth: 2,
    borderColor: "rgba(176, 133, 245, 0.4)",
    backgroundColor: "#7B1FA2",
    shadowColor: "#7B1FA2",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
  },
  brandLogoImage: {
    width: "100%",
    height: "100%",
    borderRadius: 32,
    backgroundColor: "#7B1FA2",
  },
  brandTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: 2,
    marginBottom: 4,
  },
  brandTagline: {
    fontSize: 10,
    color: theme.colors.textSecondary,
    fontWeight: "500",
  },
  authSectionTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#FFFFFF",
    marginBottom: 6,
    textAlign: "center",
  },
  authSectionDesc: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 16,
  },
  formStack: {
    width: "100%",
  },
  inputGroup: {
    marginBottom: 14,
  },
  inputLabel: {
    fontSize: 11,
    color: theme.colors.textSecondary,
    fontWeight: "600",
    marginBottom: 6,
  },
  inputFieldWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#090B13",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 12,
    height: 46,
    paddingHorizontal: 12,
  },
  inputIcon: {
    marginRight: 10,
  },
  authInput: {
    flex: 1,
    color: "#ECEFF1",
    fontSize: 14,
    fontWeight: "500",
    height: "100%",
  },
  signupGridFields: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 0,
  },
  gridHalf: {
    width: "48%",
  },
  unitLabel: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
    marginLeft: 4,
  },
  submitBtnContainer: {
    borderRadius: 12,
    marginTop: 16,
    overflow: "hidden",
    shadowColor: "#7B1FA2",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  submitBtn: {
    height: 46,
    alignItems: "center",
    justifyContent: "center",
  },
  submitBtnText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  toggleLinkRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
  },
  toggleText: {
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  toggleBtnText: {
    fontSize: 12,
    color: "#B085F5",
    fontWeight: "700",
  },
  errorText: {
    color: "#FF5252",
    fontSize: 9,
    fontWeight: "700",
    marginTop: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    justifyContent: "flex-end",
  },
  pickerContainer: {
    backgroundColor: "#0F1221",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: 380,
    borderTopWidth: 1,
    borderColor: "rgba(176, 133, 245, 0.3)",
  },
  pickerHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  pickerTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  pickerCloseText: {
    color: "#B085F5",
    fontWeight: "800",
    fontSize: 14,
  },
  optionsList: {
    marginBottom: 10,
  },
  optionItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 6,
  },
  optionItemSelected: {
    backgroundColor: "rgba(123, 31, 162, 0.3)",
  },
  optionText: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.7)",
    fontWeight: "500",
  },
  optionTextSelected: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
  successModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.82)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  successModalCard: {
    width: "100%",
    maxWidth: 380,
    backgroundColor: "#0F1221",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(176, 133, 245, 0.3)",
    padding: 24,
    alignItems: "center",
  },
  successModalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#FFFFFF",
    marginBottom: 8,
    textAlign: "center",
  },
  successModalSubtext: {
    fontSize: 13,
    color: "rgba(255, 255, 255, 0.7)",
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 18,
  },
  successModalBtn: {
    width: "100%",
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: "#7B1FA2",
    alignItems: "center",
  },
  successModalBtnText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 14,
  },
});
