import { StyleSheet, Dimensions } from 'react-native';
import theme from '../../theme/theme';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#060813',
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: theme.spacing.lg,
    paddingBottom: 50,
  },
  glowPurple: {
    position: 'absolute',
    top: -100,
    left: -100,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: 'rgba(123, 31, 162, 0.25)',
    opacity: 0.8,
  },
  glowBlue: {
    position: 'absolute',
    bottom: -100,
    right: -100,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: 'rgba(41, 182, 246, 0.2)',
    opacity: 0.8,
  },
  authCard: {
    width: '100%',
    backgroundColor: 'rgba(18, 22, 38, 0.85)',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    padding: theme.spacing.lg,
    elevation: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 24,
  },
  brandHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  brandLogoRing: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#7B1FA2',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    shadowColor: '#7B1FA2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
  },
  brandTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 2,
    marginBottom: 4,
  },
  brandTagline: {
    fontSize: 10,
    color: theme.colors.textSecondary,
    fontWeight: '500',
  },
  authSectionTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 6,
    textAlign: 'center',
  },
  authSectionDesc: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 16,
  },
  formStack: {
    width: '100%',
  },
  inputGroup: {
    marginBottom: 14,
  },
  inputLabel: {
    fontSize: 11,
    color: theme.colors.textSecondary,
    fontWeight: '600',
    marginBottom: 6,
  },
  inputFieldWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#090B13',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    height: 46,
    paddingHorizontal: 12,
  },
  inputIcon: {
    marginRight: 10,
  },
  authInput: {
    flex: 1,
    color: '#ECEFF1',
    fontSize: 14,
    fontWeight: '500',
    height: '100%',
    outlineStyle: 'none',
  },
  signupGridFields: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 0,
  },
  gridHalf: {
    width: '48%',
  },
  unitLabel: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 4,
  },
  goalSelectorContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#090B13',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 3,
    height: 46,
    alignItems: 'center',
  },
  goalOption: {
    flex: 1,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  activeGoalOption: {
    backgroundColor: '#7B1FA2',
  },
  goalText: {
    color: theme.colors.textSecondary,
    fontSize: 10,
    fontWeight: '700',
  },
  activeGoalText: {
    color: '#FFFFFF',
  },
  submitBtnContainer: {
    borderRadius: 12,
    marginTop: 16,
    overflow: 'hidden',
    shadowColor: '#7B1FA2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  submitBtn: {
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  toggleLinkRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  toggleText: {
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  toggleBtnText: {
    fontSize: 12,
    color: '#B085F5',
    fontWeight: '700',
  },
  // Validations & Custom Dropdowns
  errorText: {
    color: '#FF5252',
    fontSize: 9,
    fontWeight: '700',
    marginTop: 4,
    marginLeft: 4,
  },
  pickerModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  pickerModalContent: {
    backgroundColor: '#0F121E',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    maxHeight: '60%',
    width: '100%',
    maxWidth: 440,
    paddingBottom: 30,
  },
  pickerModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  pickerModalTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  pickerModalList: {
    padding: 16,
  },
  pickerModalOption: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.04)',
  },
  pickerModalOptionActive: {
    backgroundColor: 'rgba(123, 31, 162, 0.15)',
    borderColor: 'rgba(176, 133, 245, 0.25)',
  },
  pickerModalOptionText: {
    color: '#ECEFF1',
    fontSize: 13,
    fontWeight: '500',
  },
  pickerModalOptionTextActive: {
    color: '#B085F5',
    fontWeight: '700',
  },
});
