import { StyleSheet } from 'react-native';
import theme from '../../theme/theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#060813',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  resourcesHeader: {
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.xl,
    paddingBottom: theme.spacing.sm,
  },
  headerActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  headerProfileAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 12,
  },
  headerTitleText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  bellBtn: {
    position: 'relative',
    padding: 4,
  },
  bellBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: '#FF4081',
    borderRadius: 5,
    width: 10,
    height: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: {
    color: 'white',
    fontSize: 6,
    fontWeight: 'bold',
  },
  searchForm: {
    flexDirection: 'row',
    marginHorizontal: theme.spacing.lg,
    marginVertical: theme.spacing.sm,
    height: 46,
  },
  searchInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#090B13',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: 12,
    marginRight: 10,
  },
  searchBarIcon: {
    marginRight: 8,
  },
  searchInputField: {
    flex: 1,
    color: '#ECEFF1',
    fontSize: 13,
    fontWeight: '500',
    height: '100%',
    outlineStyle: 'none',
  },
  searchSubmitBtn: {
    backgroundColor: '#7B1FA2',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  searchSubmitBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  filtersTabRow: {
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: 10,
  },
  filterTabBtn: {
    backgroundColor: 'rgba(22, 28, 45, 0.7)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginRight: 8,
  },
  activeFilterTabBtn: {
    backgroundColor: '#7B1FA2',
    borderColor: '#7B1FA2',
  },
  filterTabBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.colors.textSecondary,
  },
  activeFilterTabBtnText: {
    color: '#FFFFFF',
  },
  videoCardsGrid: {
    paddingHorizontal: theme.spacing.lg,
    marginTop: 10,
  },
  videoResourceCard: {
    backgroundColor: 'rgba(22, 28, 45, 0.7)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 24,
    marginBottom: 20,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
  },
  videoThumbnailWrapper: {
    height: 180,
    position: 'relative',
    backgroundColor: '#0F121E',
  },
  videoThumbnailImg: {
    width: '100%',
    height: '100%',
  },
  videoPlayOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  playButtonRing: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#7B1FA2',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#7B1FA2',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
  },
  videoCardDetails: {
    padding: 16,
  },
  videoCardTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  videoCardDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dateIconSvg: {
    marginRight: 6,
  },
  videoCardDate: {
    fontSize: 10,
    color: theme.colors.textSecondary,
    fontWeight: '600',
  },
  emptyResultsBox: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyResultsText: {
    color: theme.colors.textSecondary,
    fontSize: 13,
    fontWeight: '500',
    marginBottom: 16,
  },
  clearSearchBtn: {
    backgroundColor: 'rgba(123, 31, 162, 0.15)',
    borderWidth: 1,
    borderColor: '#7B1FA2',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  clearSearchBtnText: {
    color: '#B085F5',
    fontSize: 12,
    fontWeight: '700',
  },
  videoPlayerModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: theme.spacing.md,
  },
  videoPlayerModalContent: {
    width: '100%',
    backgroundColor: '#111422',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 16,
    position: 'relative',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.5,
    shadowRadius: 30,
  },
  videoModalCloseBtn: {
    position: 'absolute',
    top: 12,
    right: 12,
    zIndex: 10,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 16,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoViewportWrapper: {
    width: '100%',
  },
  videoModalTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 12,
    paddingRight: 32,
  },
  modalVideoTag: {
    width: '100%',
    height: 200,
    borderRadius: 12,
    backgroundColor: '#000000',
  },
  videoModalMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
  },
  videoModalMetaText: {
    fontSize: 10,
    color: theme.colors.textSecondary,
    fontWeight: '600',
    marginLeft: 6,
  },
});
